### ISSUE TITLE
Отдельный шаблон для дочерних комментариев

### ISSUE THREAD

**Issue by TITAN-UZ** [bezumkin/Tickets#121]
Шаблон дочерниных  комментариев повторяет  стандартный шаблон комментария и не позволяет  изменит вид.
Решил проблему с css hide.
<code>
.hidden {
    visibility: hidden;
}
</code>

При кодирования получается длинный код  да это работа верстальщика это без спорно но отдельный чанк для субкоммента облегчил бы многих проблем начинающих верстальщиков 

P.S.

Думаю ненужные теги тоже реагирует на скорость работы  сайта

**Comment by bezumkin** [comment]
Все комментарии - это обычный список ul li, можно отдельно задавать стили для каждого уровня вложения.

Разных чанков не должно быть, потому что это всё - комментарии. Одна сущность, а не несколько, они все равны.

Перекладывать работу верстальщиков на программистов считаю неправильным.
