### ISSUE TITLE
Lexicon без загрузки

### ISSUE THREAD

**Issue by sergant210** [bezumkin/Tickets#123]
А без загрузки лексикона будет работать такой код?
```
$response = $modx->toJSON(array('success' => false, 'message' => $modx->lexicon($message)));
```
https://github.com/bezumkin/Tickets/blob/master/assets/components/tickets/action.php#L77

**Comment by bezumkin** [comment]
Лексикон загружается на [49 строке](https://github.com/bezumkin/Tickets/blob/master/assets/components/tickets/action.php#L49) при инициализации класса Tickets.
