### ISSUE TITLE
Если секция находится в группе ресурсов - выдает ошибку

### ISSUE THREAD

**Issue by but1head** [bezumkin/Tickets#127]
Есть группы пользователей и ресурсов (company / user)
Если секцию тикетов добавить в эти группы, то при создании тикета через TicketForm получаю ошибку "Неверный раздел для тикета" ну и не ищет эту секцию в parent

**Comment by bezumkin** [comment]
Полагаю, что у групп нет разрешения для публикации тикетов в эти секции. Должно быть ** section_add_children**

**Comment by but1head** [comment]
Стоит TicketUserPolicy , более ничего не видел в доках, где это запись должна быть?

**Comment by bezumkin** [comment]
Там есть еще и **TicketsSectionPolicyTemplate**.

**Comment by but1head** [comment]
В доках не нашел, http://docs.modx.pro/search?query=TicketsSectionPolicyTemplate

Но спасибо, разобрался.

**Comment by bezumkin** [comment]
Раз разобрался - [пришли информацию в доки](https://github.com/bezumkin/Docs/blob/master/Contributing.md), я её с удовольствием добавлю.
