### ISSUE TITLE
500 ошибка в менеджере при попытке создания тикета

### ISSUE THREAD

**Issue by hichnicksemen** [bezumkin/Tickets#138]
Выдаёт ошибку: "Сайт пока не может обработать этот запрос. 500" при нажатии кнопки "Создать тикет" в категории с количеством документов 2800 штук. 
В остальных категориях всё в порядке, но там меньше 1000 ресурсов.
В логах всё чисто.

Версия Tickets 1.6.16-pl
Версия MODX 2.5.0-pl

**Comment by bezumkin** [comment]
Почти 7000 вопросов на modx.pro - нет проблем.
<img width="1044" alt="2016-05-12 17 29 51" src="https://cloud.githubusercontent.com/assets/1257284/15211745/458ddb6c-1867-11e6-8850-e99acd43cdca.png">
<img width="1056" alt="2016-05-12 17 30 05" src="https://cloud.githubusercontent.com/assets/1257284/15211746/45904b4a-1867-11e6-8adc-18b4095b40a7.png">
Ошибку 500 нужно искать в логе своего сервера.
