### ISSUE TITLE
Возможность передать свой URL для ветки(родителя) комментариев

### ISSUE THREAD

**Issue by manicko** [bezumkin/Tickets#61]
По следам вот этого обсуждения: http://bezumkin.ru/sections/components/2595/#comment-21528

Укажите, пожалуйста, в описании к Tiсkets, что комментирование доступно для документов в своих таблицах, часто это важный критерий при выборе.

**Comment by bezumkin** [comment]
https://github.com/bezumkin/Tickets/commit/dc4b55413424363d071a2846af6cbbf62e860bd9
