### ISSUE TITLE
Вырубить Jevix

### ISSUE THREAD

**Issue by Kidokyfe** [bezumkin/Tickets#64]
В настройках для всех ресурсов выключил Jevix в ресурсе который я создал я его тоже выключил. И если для поля **[[*content]]** он перестал работать то для **[[*introtext]]** он все еще включен. Как то это не правильно.

**Comment by neonoviy** [comment]
Вроде как та же история. Jevix выключен везде: в настройках раздела тикетов и в самом тикете. Он нужен мне исключительно для комментариев. Но при сохранении тикета с пустым интротекстом, в него попадает контент.

Я хочу, чтоб в блоге, при наличии интротекста, он отображался со ссылкой далее, а при его отсутствии, отображался бы контент. У description есть ограничение в 255 символов - оно не подходит. Вроде ж логично, что при отключении jevix в интротекст не должно ничего записываться, или тут какая-то другая логика?
