### ISSUE TITLE
Теги для Тикетов

### ISSUE THREAD

**Issue by vasilueff** [bezumkin/Tickets#83]
Было бы здорово прикрутить тэги. Т.е., при создании тикета пользователь заполняет поле "тэги" - аналогичный механизм создан в miniShop2. Заполнив один раз поле "тэги", при следующем заполнении мы получаем автоподстановку при наборе слова. Например, один раз ввели слово "краска", когда пользователь при создании другого тикета похожей тематики начинает вводить слово "краска" - система предлагает это слово в списке. 

Этот механизм позволит сортировать тикеты по тэгам, выводить "похожее", создавать подписки на интересующие тэги и многое другое. 

 Заранее благодарен.

**Comment by PatSpiegel** [comment]
https://modx.pro/help/4531/

**Comment by bezumkin** [comment]
https://modx.pro/work/2523-vasily-write-tags-and-karma-for-tickets/
https://modx.pro/crowdfunding/4543-tags-to-tickets/

**Comment by mvoevodskiy** [comment]
Если закомментировать 5 строку в файле assets/components/tickets/js/mgr/ticket/update.js
(https://github.com/bezumkin/Tickets/blob/master/assets/components/tickets/js/mgr/ticket/update.js#L5)
, то на странице редиктирования тикета в админке пропадает вкладка "Комментарии", но начинает корректно работать сторонний компонент Tagger, который уже имеет мощные механизмы работы с тегами.

Возможно, это в чем-то поможет.

**Comment by bezumkin** [comment]
Теперь можно использовать Tagger или любой другой подобный компонент
[![](https://file.modx.pro/files/2/1/5/21574630bedb9b36c7c35831f68bae39s.jpg)](https://file.modx.pro/files/2/1/5/21574630bedb9b36c7c35831f68bae39.png)
