### ISSUE TITLE
Еще одна вкладка в админке

### ISSUE THREAD

**Issue by vasilueff** [bezumkin/Tickets#87]
Василий, хочу предложить такую идею - добавить в админке еще одну вкладку для тикетов "Все тикеты". Сейчас можно увидеть все комментарии и комментарии сгруппированные по "веткам" комментариев. Для чего нужна новая вкладка? Когда тикеты используются для блого-социального проекта, нужно видеть кто и куда прислал публикации, отдельные материалы или новости, а ползать по всем разделам в поисках неопубликованных тикетов, согласись, не удобно. 

В новой вкладке хотелось бы увидеть сортировку по опубликованным, не опубликованным и по дате размещения.

 Заранее благодарен.

**Comment by bezumkin** [comment]
[![](https://file.modx.pro/files/5/d/c/5dcb63e50e5b05cb1de648a3b60929f8s.jpg)](https://file.modx.pro/files/5/d/c/5dcb63e50e5b05cb1de648a3b60929f8.png)
