### ISSUE TITLE
Цифры вмеcто алиаса у тикетов

### ISSUE THREAD

**Issue by gavandrei** [bezumkin/Tickets#91]
При создании тикета вместо алиаса контейнера в uri подставляется его id.
Такое поведение наблюдается если настройка automatic_alias не установлена.
Это фича или баг? Т.к. к примеру мне не нужна авто генерация алиасов, но нужно чтобы вместо id был алис категории в uri тикета.

Данную проблему можно решить передавая алиас категории в функцию getAliasPath в классе Tiket.

Строка 442
$uri = rtrim($section->getAliasPath(),'/') .'/'. str_replace($pls['pl'], $pls['vl'], $template);
заменить на
$uri = rtrim($section->getAliasPath($section->get('alias')),'/') .'/'. str_replace($pls['pl'], $pls['vl'], $template);

**Comment by bezumkin** [comment]
Fixed #115
