### ISSUE TITLE
Поле introtext, в тикете, игнорируется ВКЛючение "Выполнять теги MODX" (теги не выполняются)

### ISSUE THREAD

**Issue by akimsullec** [bezumkin/Tickets#96]
Привет!
Работаю через бэкенд.
Для содержимого поля introtext игнорируется включение "Выполнять теги MODX" - квадратные скобки подменяются на \&#91; и \&#93; (для этого после сохранения тикета нужно обновить страницу).

И ещё, в поле introtext при сохранении документа происходит форматирование содержимого.
Например, при вЫключенном "Выполнять теги MODX", если в поля introtext и content  поместить:
<code>[[$chunk]]\<p\> \</p\></code>
, то после сохранения документа и обновления страницы (!) содержимое меняется:
В introtext на 
<code>\&#91;\&#91;$chunk\&#93;\&#93;\<br\></code>
, в content на 
<code>\&#91;\&#91;$chunk\&#93;\&#93;\<p\> \</p\></code>

То есть в introtext происходит форматирование Jevix`ом всего содержимого, а в content только форматирование тэгов. При отображении страницы в браузере, содержимое поля content отображается корректно, в соответствии с насройками Jevix, однако в выводе списка тикетов вместо содержимого чанка мы видим, естественно, тэг чанка.

Воссоздано по мотивам реальных событий вот тут:

Панель управления	http://s6177.test.modx.pro/manager/
Логин	s6177
Пароль	_u1BIy0s8AQJ

**Comment by bezumkin** [comment]
Fixed #115

**Comment by bezumkin** [comment]
Если включена обработка Jevix и introtext пуст, то в него попадает обработанный content для вывода на страницах сайта в списке тикета.

А при обработке Jevix пустой тег `<p> </p>` вырезается.
